// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// hispa_analyze_cpp
bool hispa_analyze_cpp(std::string input_file, std::string output_dir, int mcmc_iterations, int num_clusters, int mcmc_burn_in, double mcmc_initial_sd, double mcmc_sd_floor, double mcmc_sd_ceil, bool use_cluster_init, int cluster_init_iterations, double cluster_initial_sd, bool save_samples, int sample_interval, bool verbose);
RcppExport SEXP _HiSpaR_hispa_analyze_cpp(SEXP input_fileSEXP, SEXP output_dirSEXP, SEXP mcmc_iterationsSEXP, SEXP num_clustersSEXP, SEXP mcmc_burn_inSEXP, SEXP mcmc_initial_sdSEXP, SEXP mcmc_sd_floorSEXP, SEXP mcmc_sd_ceilSEXP, SEXP use_cluster_initSEXP, SEXP cluster_init_iterationsSEXP, SEXP cluster_initial_sdSEXP, SEXP save_samplesSEXP, SEXP sample_intervalSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type input_file(input_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_dir(output_dirSEXP);
    Rcpp::traits::input_parameter< int >::type mcmc_iterations(mcmc_iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type num_clusters(num_clustersSEXP);
    Rcpp::traits::input_parameter< int >::type mcmc_burn_in(mcmc_burn_inSEXP);
    Rcpp::traits::input_parameter< double >::type mcmc_initial_sd(mcmc_initial_sdSEXP);
    Rcpp::traits::input_parameter< double >::type mcmc_sd_floor(mcmc_sd_floorSEXP);
    Rcpp::traits::input_parameter< double >::type mcmc_sd_ceil(mcmc_sd_ceilSEXP);
    Rcpp::traits::input_parameter< bool >::type use_cluster_init(use_cluster_initSEXP);
    Rcpp::traits::input_parameter< int >::type cluster_init_iterations(cluster_init_iterationsSEXP);
    Rcpp::traits::input_parameter< double >::type cluster_initial_sd(cluster_initial_sdSEXP);
    Rcpp::traits::input_parameter< bool >::type save_samples(save_samplesSEXP);
    Rcpp::traits::input_parameter< int >::type sample_interval(sample_intervalSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(hispa_analyze_cpp(input_file, output_dir, mcmc_iterations, num_clusters, mcmc_burn_in, mcmc_initial_sd, mcmc_sd_floor, mcmc_sd_ceil, use_cluster_init, cluster_init_iterations, cluster_initial_sd, save_samples, sample_interval, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HiSpaR_hispa_analyze_cpp", (DL_FUNC) &_HiSpaR_hispa_analyze_cpp, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_HiSpaR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
